### ISSUE TITLE
Possible bug introduced by swapping process.env

### ISSUE THREAD

**Issue by rwjblue** [medikoo/process-utils#1]
I happened across this library while searching for a package that has this exact functionality today, thanks for putting it together!

One thing I noticed is that the implementation sets `process.env = {}` then restores the original value when the callback function is called. I was quite surprised to find this out myself, but setting `process.env` to another object actually **breaks** some of the functionality in ways that might cause your library users to have issues.

Specifically, setting `process.env` to `{}` breaks the string coercion that is normally done by `process.env`. Here are some test examples, the ones before `process.env = {}` pass and the ones after (though they are **_exactly_** the same) fail.

```js
const assert = require('assert');

process.env.FOO = true;
assert.equal(process.env.FOO, 'true');

process.env.FOO = false;
assert.equal(process.env.FOO, 'false');

process.env.FOO = undefined;
assert.equal(process.env.FOO, 'undefined');

process.env.FOO = 1;
assert.equal(process.env.FOO, '1');

// now clobber process.env, and test again
process.env = {};

process.env.FOO = true;
assert.equal(process.env.FOO, 'true');

process.env.FOO = false;
assert.equal(process.env.FOO, 'false');

process.env.FOO = undefined;
assert.equal(process.env.FOO, 'undefined');

process.env.FOO = 1;
assert.equal(process.env.FOO, '1');
```

---

In my real world project where I needed this reset functionality I ended up doing:

```js
function resetProcessEnv(originalProcessEnv) {
  for (let key in process.env) {
    if (key in originalProcessEnv) {
      process.env[key] = originalProcessEnv[key];
    } else {
      delete process.env[key];
    }
  }

  for (let key in originalProcessEnv) {
    if (!(key in process.env)) {
      process.env[key] = originalProcessEnv[key];
    }
  }
}

let originalProcessEnv = Object.assign({}, process.env);

// do mutations
resetProcessEnv(originalProcessEnv);
```

---

Hope this helps! Thanks for taking the time to write up a useful library 😄

**Comment by medikoo** [comment]
Indeed, the counterpart object doesn't reflect same behavior. Luckily `restoreEnv()`, works as expected (and brings back properly behaving env object).

Anyway that's a bug. Thanks for report!
